apiVersion: apps/v1
kind: Deployment
metadata:
  name: okteto/vote
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: okteto/vote
  template:
    metadata:
      labels:
        app: okteto/vote
    spec:
      containers:
      - image: docker.io/dahir4477/okteto/vote
        name: okteto/vote
        ports:
        - containerPort: 80
