apiVersion: apps/v1
kind: Deployment
metadata:
  name: okteto/sample-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: okteto/sample-app
  template:
    metadata:
      labels:
        app: okteto/sample-app
    spec:
      containers:
      - image: docker.io/dahir4477/okteto/sample-app:v1
        name: vote-ui
        ports:
        - containerPort: 80
